<div class="row">
          <div class="card-login">
          <div class="card">
            <div class="card-header">
              Login
            </div>
            <div class="card-body">
              <form method="post" action="autentica_usuario">
                <div class="form-group" >
                  <input name="email" type="text" class="form-control" placeholder="Usuario">
                </div>
                <div class="form-group">
                  <input name="senha" type="password" class="form-control" placeholder="Senha">
                </div>
                <?php if (isset($_GET['login'])) {
                  if ($_GET['login'] == 'erro') { ?>
                  <div class="text-danger">
                    Usuario ou senha invalido
                  </div>
                <?php 
              }
            } ?> 
                <?php if (isset($_GET['login'])) {
                  if ($_GET['login'] == 'erro2') { ?>
                  <div class="text-danger">
                    E necesario fazer login antes
                  </div>
                <?php 
              }
            } ?> 
                <button  class="btn btn-lg btn-info btn-block" type="submit">Entrar</button>
              </form>
              <?php if (isset($_GET['logoff'])) {
                if ($_GET['logoff'] == 'ok') { ?>
                  <div class="text-center text-success">
                    Logoff realizado!
                  </div>
                <?php 
              }
            } ?> 
            </div>
          </div>
        </div>