<div class="row">
      <div class="card-abrir-chamado">
        <div class="card">
          <div class="card-header">
            Adicionar Usuario
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col">
                <form method="post" action="/cadastrar_user">
                  <div class="form-group">
                      <label>Nome</label>
                      <input name="nome" type="text" class="form-control" placeholder="Nome">
                    </div>  
                  <div class="form-group">
                    <label>E-mail</label>
                    <input name="email" type="email" class="form-control" placeholder="E-mail">
                  </div>
                  <div class="form-group">
                    <label>Senha</label>
                    <input name="senha" type="password" class="form-control" placeholder="Senha">
                  </div>
                  <div class="form-group">
                    <label>Tipo Usuario</label>
                    <select name="tipo" class="form-control">
                      <option>Selecione o tipo do usuario</option>
                      <option value="1">Administrador</option>
                      <option value="2">Usuario</option>
                    </select>
                    
                  </div>
                  <?php if(isset($_GET['criou'])){ ?>
                  <div class="row mt-5">
                    <div class="col">
                    <?php if(($_GET['criou'] == 'true')) { ?>
                      <h2 class="text-success">Usuario criado com sucesso.</h2>
                    <?php }else {?>
                      <h2 class="text-danger">Email já cadastrado na aplicação.</h2>
                    <?php }?>
                    </div>
                  </div>
                      <?php }?>
                  <div class="row mt-5">
                    <div class="col-6">
                      <a class="btn btn-lg btn-warning btn-block" href="/home">Voltar</a>
                    </div>
                    <div class="col-6">
                      <button class="btn btn-lg btn-info btn-block" type="submit">Cadastrar</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    
    <script src="js/bootstrap.min.js"></script>
